# Site settings
title: m3talm3rg3
email: your-email@domain.com
url: https://m3talm3rg3.github.io
description: "Site which contains articles about hacking, pentesting, red team and hackthebox platform solutions write-ups by m3talm3rg3"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://m3talm3rg3.github.io/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/m3talm3rg3

# Build settings
markdown: kramdown
permalink: pretty
